-- CrisisGuard — Phase 8: Hive Table Creation DDL
-- Author: B.SIVASAI (Roll Number: 2023BCS0228)
-- Course: CSE412 — Big Data & Large-Scale Computing
-- Project: CrisisGuard: A Real-Time Big Data Pipeline for Synthetic Media
--          Propagation Analysis and Emergency Response Prioritization

CREATE DATABASE IF NOT EXISTS crisisguard_phase8
LOCATION 'hdfs://localhost:9000/crisisguard/phase8/hive/';

USE crisisguard_phase8;

-- 1. Table: propagation_graph_metrics (Generated by GraphX)
DROP TABLE IF EXISTS propagation_graph_metrics;
CREATE EXTERNAL TABLE IF NOT EXISTS propagation_graph_metrics (
    vertex_id BIGINT,
    node_name STRING,
    pagerank DOUBLE,
    component_id BIGINT,
    in_degree BIGINT,
    out_degree BIGINT
)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/crisisguard/phase8/graph/metrics_parquet/';

-- 2. Table: propagation_stream_metrics (Generated by Spark Structured Streaming)
DROP TABLE IF EXISTS propagation_stream_metrics;
CREATE EXTERNAL TABLE IF NOT EXISTS propagation_stream_metrics (
    scenario_id STRING,
    window_event_count BIGINT,
    unique_source_nodes BIGINT,
    unique_target_nodes BIGINT,
    mean_synthetic_risk DOUBLE,
    max_synthetic_risk DOUBLE,
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    propagation_rate_per_min DOUBLE
)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/crisisguard/phase8/streaming/windowed_metrics/';

-- 3. Table: media_risk_features (Phase 6 Synthetic Media Risk Outputs)
DROP TABLE IF EXISTS media_risk_features;
CREATE EXTERNAL TABLE IF NOT EXISTS media_risk_features (
    content_id STRING,
    media_type STRING,
    model_branch STRING,
    model_version STRING,
    model_score DOUBLE,
    synthetic_probability DOUBLE,
    synthetic_risk DOUBLE,
    calibration_status STRING,
    prediction_timestamp STRING,
    source_dataset STRING,
    quality_status STRING,
    provenance STRING
)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/crisisguard/phase8/media_risk/';

-- 4. Table: crisis_intelligence_features (Phase 7 Unified Crisis Features)
DROP TABLE IF EXISTS crisis_intelligence_features;
CREATE EXTERNAL TABLE IF NOT EXISTS crisis_intelligence_features (
    content_id STRING,
    source_dataset STRING,
    source_record_id STRING,
    event_id STRING,
    text_available BOOLEAN,
    image_available BOOLEAN,
    crisis_category STRING,
    task_name STRING,
    model_score DOUBLE,
    confidence DOUBLE,
    quality_status STRING,
    calibration_status STRING,
    temporal_features STRING,
    context_features STRING,
    provenance STRING,
    model_version STRING,
    prediction_timestamp STRING,
    governance_type STRING
)
STORED AS PARQUET
LOCATION 'hdfs://localhost:9000/crisisguard/phase8/crisis_intelligence/';
